# Generated by Django 5.0.1 on 2024-02-13 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0006_alter_task_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="task",
            managers=[],
        ),
    ]
